### ISSUE TITLE
Für Windows als eigenständiges Programm (.exe)

### ISSUE THREAD

**Issue by korbball** [romixch/SchirizettelGenerator#1]
Schirizettell Generator eigenständiges Programm für Windows.
- Ohne Java
- ohne Installation
- Als .exe

**Comment by romixch** [comment]
Könnte wohl mit folgendem Blogpost gelöst werden: https://github.com/raeleus/skin-composer/wiki/libGDX-and-JPackage

**Comment by romixch** [comment]
Release ist nun eine Zip-Datei, die entpackt werden kann. Dokumentation steht noch aus.

**Comment by romixch** [comment]
Auch die Doku ist nachgeführt.
