### ISSUE TITLE
Templates / Vorlagen in Software integrieren

### ISSUE THREAD

**Issue by korbball** [romixch/SchirizettelGenerator#2]
Standard Schiriblockvorlagen wie "schirizettel.rptdesign" oder "schirizettel_ohne_tenue.rptdesign" sollen z.B. aus einem Drop-Down-Menu ausgewählt werden können.

Im letzten Drop-Down-Item wird dann der Pfad zur Benutzervorlage selbst gewählt.

Die Vorlagen sollen dann im Programm integiert sein ohne dass diese separat Heruntergeladen werden müssen.

**Comment by romixch** [comment]
Gute Idee. Macht die Benutzung sicher einiges einfacher. Ist es überhaupt noch notwendig, ein eigenes Design auswählen zu können, wenn die Vorlagen einigermassen gut sind?
Ich könnte eine für A4 und eine für A5 erstellen.

**Comment by korbball** [comment]
A5 hatte ich bereits erstellt - kann ich dir senden.
- Auswahl ob mit/ohne Tenu -> Wenn nicht, dann soll "Farbe" dort stehen
- Wir haben z.B. Keine Zeitnehmer
- mit/ohne Linienrichter

Könne man allerdings auch mit Checkboxen als Option geben.
Hier ein Bild wie die Blöcke im Thurgau aussehen:
![grafik](https://user-images.githubusercontent.com/55682823/67835424-33cee880-faea-11e9-9c36-898cad866b53.png)
 
Vorlagen von dir gefallen mir sonst sehr gut.

**Comment by romixch** [comment]
Ich habe nun daran gearbeitet, die Vorlage anders zu machen. BIRT scheint nicht mehr ein sehr aktives Projekt zu sein. Darum habe ich das nun simpler gemacht:
Als Vorlage dient nun ein PDF mit Formularfeldern. Das kann man einfach mit LibreOffice oder wahrscheinlich auch mit Word erstellen. Das Programm wird daruch auch viel kleiner (nur noch 1/10). Die Vorlage kannst du dir hier mal anschauen: (https://github.com/romixch/SchirizettelGenerator/tree/master/src/main/resources)
Damit lässt sich dann auch ein einzelnes Jar erstellen, das du nur doppelklicken kannst.
Ein fertiges Release kommt aber erst später.

**Comment by korbball** [comment]
Mit der PDF Vorlage hört sich nicht schlecht an, allerdings gefiel mir der strukturierte Aufbau von BIRT. Womit das PDF erstellt wird spielt ja keine Rolle solange die Felder übereinstimmen.

Optimal wäre natürlich, wenn man bei Anpassungen am Zettel den Vorgang nicht 3mal machen müsste. Oder gleich nur eine Zettelvorlage und anhand der Anzahl Blöcke oder dem Ausgabeformat (A4, A5) wird dieser dann auf dem Blatt verteilt.

**Comment by romixch** [comment]
Das sehe ich schon auch. Die Frage ist halt der Aufwand. Ich kann das unendlich weit ziehen hier. Der Aufwand steigt aber dann auch ins unendliche.
Mit den PDFs kriege ich was hin, womit normale User arbeiten können. Ich kann auch prüfen, welche Felder im PDF sind, wieviele Zettel pro Blatt es sind und ob es mit dem CSV übereinstimmt. Dann kann ich entsprechende Rückmeldungen geben.
So schaffe ich es mit einem vertretbaren Aufwand was zu liefern, womit die Leute selber arbeiten können.
Werde den PDF-Weg weiter gehen. Unser Formular baue ich gleich ein. Wenn du mir weitere PDF-Formulare lieferst, kann ich die auch einbauen.

**Comment by korbball** [comment]
Alles Klar, das macht Sinn.

> ch kann auch prüfen, welche Felder im PDF sind, wieviele Zettel pro Blatt es sind und ob es mit dem CSV übereinstimmt. Dann kann ich entsprechende Rückmeldungen geben.

Gefällt mir!

Sind deine Vorlagen bereits Fertig?
[https://github.com/romixch/SchirizettelGenerator/tree/master/src/main/resources](url)

**Comment by romixch** [comment]
Mit dem Neuen Release habe ich nun zwei Vorlagen integriert. Markiere diesen Issue mal als geschlossen. Kannst mir deine Vorlage ja immer noch schicken.

**Comment by korbball** [comment]
Sieht schon mal richtig gut aus!
Als Info: Word kann keine Formulare als PDF abspechern.
Mit LibreOffice ist dies aber möglich und auch kostenlos.
https://www.youtube.com/watch?v=-zLTSaIL9N0
