### ISSUE TITLE
CSV Import verbessern:

### ISSUE THREAD

**Issue by korbball** [romixch/SchirizettelGenerator#4]
Aktuell muss das CSV gemäss Beispieldatei sein also `"String"`.
Bei Excel sieht das aber so aus mit:
`Date;Time;Category;Hall;TeamA;TeamB;TenuA;TenuB;TrousersA;TrousersB;PreviousTeamA;PreviousTeamB
09.11.2019;08:00;Knaben;Halle 1;STV Zihlschlacht U16;KB Altnau U14;Tenu;Tenu;Trousers;Trousers;;`

oder mit Komma:
`Date,Time,Category,Hall,TeamA,TeamB,TenuA,TenuB,TrousersA,TrousersB,PreviousTeamA,PreviousTeamB
09.11.2019,08:00,Knaben,Halle 1,STV Zihlschlacht U16,KB Altnau U14,Tenu,Tenu,Trousers,Trousers,,`

Aber mit `"String" `wird es nie ausgegeben.

Importer sollte Trennzeichen erkennen: `;` oder `,`
und Strings mit oder ohne `""`

Fehlende Felder sollen übersprungen werden.

Optional:
Beim öffnen der CSV-Datei kann der Benutzer die Überschriften selber zuordnen, was fehlt das fehlt und Rechtschreibefehler sind dem Importer egal.

**Comment by romixch** [comment]
Ich denke, das ist mit der neusten Version nun auch zweckmässig erledigt.
