### ISSUE TITLE
Templates & CSV und speicher Ort auf Desktop

### ISSUE THREAD

**Issue by korbball** [romixch/SchirizettelGenerator#5]
Ich persönlich fände es praktischer, wenn alle Vorlagen vom Desktop aus geöffnet werden könnten.
Aktuell muss man sich durchklicken oder die Dateien im `\SchirizettelGenerator\bin` speichern.

Ob das auch für Linux und Apple funktioniert weiss ich leider nicht.

**Comment by romixch** [comment]
Normalerweise wird der Dokumente-Ordner empfohlen. Müsste jetzt so konfiguriert sein. Hab's auf Windows aber nocht getestet.
