### ISSUE TITLE
Fehler beim speichern als PDF

### ISSUE THREAD

**Issue by korbball** [romixch/SchirizettelGenerator#6]
- [x] 1. Wenn man beim "Datei öffnen" den neuen namen ohne `.pdf` eingibt, wird folgender Fehler generiert: ![grafik](https://user-images.githubusercontent.com/55682823/68991240-cac2d100-085c-11ea-80f2-d2f1bae0b4cc.png) ![grafik](https://user-images.githubusercontent.com/55682823/68991258-1f664c00-085d-11ea-82b1-9ea6fa4ac136.png)

Deine Formulierung ist aus meiner Sicht absolut korrekt, für normal Anwender würde ich aber Begriffe vorschlagen, welche geläufiger sind.
- [x] 2. Kosmetik: `Datei öffnen` ändern in `Speichern unter`

- [x] 3. Kosmetik: "Wähle, wohin die PDF-Datei gespeichert wird"

**Comment by romixch** [comment]
Alles gelöst. Obwohl ich den ersten Fehler nicht ganz nachvollziehen konnte. Mich irritieren die ersten paar Zeichen vor Date. Vielleicht ist kannst du mir die entsprechende CSV-Datei mal schicken. Das muss da ganz am Anfang der Datei stehen.

**Comment by korbball** [comment]
Hab es heuet wieder einmal ausprobiert. Wenn man beim Speichern unter den Namen eingibt und bestätigt, wird der suffix nicht im Pfad angegeben.

![grafik](https://user-images.githubusercontent.com/55682823/75605826-ba222800-5ae6-11ea-9286-ab05bf63e7ad.png)

![grafik](https://user-images.githubusercontent.com/55682823/75605831-c5755380-5ae6-11ea-8653-268186612cb0.png)

**Comment by romixch** [comment]
Mit Version 1.3 gelöst
