### ISSUE TITLE
Temporäre PDFs löschen

### ISSUE THREAD

**Issue by korbball** [romixch/SchirizettelGenerator#8]
Die temprären PDFs werden nachdem generieren im Ordner gespeichert - automatisch löschen.

![grafik](https://user-images.githubusercontent.com/55682823/68991528-014e1b00-0860-11ea-8b19-0fe0e9667b5b.png)

**Comment by korbball** [comment]
Werden nach dem schliessen des Programms gelöscht.

**Comment by romixch** [comment]
Die sollten ja nicht mehr stören, wenn die Speicherorte auf den Desktop zeigen.

**Comment by romixch** [comment]
Sollte jetzt nicht mehr stören, da dieses Verzeichnis gar nicht mehr angezeigt wird.
